# Generated by Django 4.2.6 on 2023-10-26 23:55

import django.core.validators
from django.db import migrations, models
import upload_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdffile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=upload_app.models.set_pdf_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('filename', models.CharField(max_length=20)),
                ('pagenumforcover', models.IntegerField()),
                ('coverpage', models.FileField(upload_to=upload_app.models.set_cover_file_name)),
                ('result', models.ImageField(upload_to='ocrresult/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('result', models.ImageField(upload_to='result/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pdfdocument', models.FileField(upload_to='pdf/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
