# Generated by Django 4.2.6 on 2023-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
